# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:18-buster

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          key: sbt-cache

      # compile, test & run
      - run:
          name: compile
          command: |
            sbt "clean;test"

      - run:
          name: assembly
          command: |
            sbt assembly

      - run:
          name: test, coverage
          command: |
            sbt xcoverage

      - run:
          name: coverage report
          command: |
            curl -Os https://uploader.codecov.io/latest/codecov-linux
            chmod +x codecov-linux
            ./codecov-linux -t ${CODECOV_TOKEN}

      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"