# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-buster

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          key: sbt-cache

      # compiler, test & run
      - run:
          name: clean, compile
          command: |
            sbt clean test:compile it:compile

      - run:
          name: test, coverage
          command: |
            sbt coverage test coverageReport

      - run:
          name: assembly
          command: |
            sbt assembly

      - run:
          name: coverage report
          command: |
            bash <(curl -s https://codecov.io/bash) -t 741c6253-b971-4e3a-99d3-31fb4afa3e6b

      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"