addSbtPlugin("com.eed3si9n"   % "sbt-assembly"           % "2.0.0")
addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.7")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"          % "0.11.0")
addSbtPlugin("com.github.sbt" % "sbt-git"                % "2.0.0")
addSbtPlugin("io.spray"       % "sbt-revolver"           % "0.9.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.5.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"          % "2.0.6")
addSbtPlugin("ch.epfl.scala"  % "sbt-bloop"              % "1.5.4-54-cfc03bdc")
