name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 11
    - name: compile
      run: sbt -v -Dfile.encoding=UTF-8 clean test:compile it:compile
    - name: tests
      run: sbt -v -Dfile.encoding=UTF-8 test
    - name: assembly
      run: sbt -v -Dfile.encoding=UTF-8 assembly
