name: Scala CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: compile
        run: sbt -v compile
      - name: compile unit tests
        run: sbt Test/compile
      - name: tests
        run: sbt test
      - name: compile integration tests
        run: sbt IntegrationTest/compile
      - name: assembly
        run: sbt assembly
      - name: dependency updates
        run: sbt xdup
