name: Scala CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup Scala and Java
        uses: coursier/setup-action@v1
        with:
          jvm: zulu@17 
      - name: compile main
        run: sbt -v -Dfile.encoding=UTF-8 --client compile
      - name: compile unit tests
        run: sbt -v -Dfile.encoding=UTF-8 --client Test/compile
      - name: tests
        run: sbt -v -Dfile.encoding=UTF-8 --client test
      - name: compile integration tests
        run: sbt -v -Dfile.encoding=UTF-8 --client IntegrationTest/compile
      - name: assembly
        run: sbt -v -Dfile.encoding=UTF-8 --client assembly
