name: Scala CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: scala cache dependencies
        uses: coursier/cache-action@v6
      - name: compile main
        run: sbt -v -Dfile.encoding=UTF-8 --client compile
      - name: compile unit tests
        run: sbt -v -Dfile.encoding=UTF-8 --client Test/compile
      - name: tests
        run: sbt -v -Dfile.encoding=UTF-8 --client test
      - name: compile integration tests
        run: sbt -v -Dfile.encoding=UTF-8 --client IntegrationTest/compile
      - name: assembly
        run: sbt -v -Dfile.encoding=UTF-8 --client assembly
      - name: dependency updates
        run: sbt -v -Dfile.encoding=UTF-8 --client dependencyUpdates
