name: Scala CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: zulu@1.17 
      - name: compile main
        run: sbt -v -Dfile.encoding=UTF-8 --client compile
      - name: compile unit tests
        run: sbt -v -Dfile.encoding=UTF-8 --client Test/compile
      - name: tests
        run: sbt -v -Dfile.encoding=UTF-8 --client test
      - name: compile integration tests
        run: sbt -v -Dfile.encoding=UTF-8 --client IntegrationTest/compile
      - name: assembly
        run: sbt -v -Dfile.encoding=UTF-8 --client assembly
