name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: compile main
      run: sbt ++2.13.6 -v -Dfile.encoding=UTF-8 --client compile
    - name: compile unit tests
      run: sbt ++2.13.6 -v -Dfile.encoding=UTF-8 --client test:compile
    - name: tests
      run: sbt ++2.13.6 -v -Dfile.encoding=UTF-8 --client test
    - name: compile integration tests
      run: sbt ++2.13.6 -v -Dfile.encoding=UTF-8 --client it:compile
    - name: assembly
      run: sbt ++2.13.6 -v -Dfile.encoding=UTF-8 --client assembly
